# Generated by Django 4.2.7 on 2024-01-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playhistory',
            name='preview_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
