# Generated by Django 4.2.7 on 2023-12-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_feedback_reason1_feedback_reason2_feedback_reason3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='reason3',
            new_name='discovery_of_new_music',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='reason4',
            new_name='favorite_artists',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='reason1',
            new_name='genre_compatibility',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='reason2',
            new_name='mood_enhancement',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='reason5',
            new_name='nostalgia',
        ),
    ]
