# Generated by Django 4.2.7 on 2023-12-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_rename_reason1_feedback_discovery_of_new_music_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='favorite_artists',
            new_name='artists',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='genre_compatibility',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='mood_enhancement',
            new_name='mood',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='discovery_of_new_music',
            new_name='new_music',
        ),
    ]
