# Generated by Django 4.2.7 on 2024-01-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_rename_favorite_artists_feedback_artists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='new_music',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='nostalgia',
        ),
    ]
