# Generated by Django 4.2.7 on 2024-01-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_remove_feedback_artists_remove_feedback_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_age_group',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_favorite_genre',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
