# Generated by Django 4.2.7 on 2024-01-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0006_feedback_user_age_group_feedback_user_favorite_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user_age_group',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user_favorite_genre',
        ),
    ]
