# Generated by Django 4.2.7 on 2024-01-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0007_remove_feedback_user_age_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_age_group_field',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_favorite_genre_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
