# Generated by Django 4.2.7 on 2024-02-29 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0008_feedback_user_age_group_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('artist_popularity', models.IntegerField()),
                ('artist_genres', models.TextField()),
                ('album_name', models.CharField(max_length=255)),
                ('track_popularity', models.IntegerField()),
                ('album_image', models.URLField()),
                ('preview_url', models.URLField(null=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.playlist')),
            ],
        ),
    ]
