# Generated by Django 4.2.7 on 2024-03-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0010_track_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
